### ISSUE TITLE
Question about granno dataset

### ISSUE THREAD

**Issue by rhythmcao** [jonathanherzig/semantic-parsing-annotation#1]
Hi,
it seems that only the training samples in version `nat` provide variables mapping types to values. But the `granno` version doesn't provide the corresponding lexicon mappings. How do we calculate the denotation accuracy without those variables due to execution error? Thanks.

**Comment by jonathanherzig** [comment]
We evaluate our models in a setting where entities are abstracted. So when training on an abstracted set, and evaluating on `nat`, the following logic tries to replace abstract entities (e.g., `_state_`, `_city_` etc.) to their actual value as in the gold example:
https://github.com/jonathanherzig/semantic-parsing-annotation/blob/a1b6a4bb9fac800ccaf2d5c342c8ba660fd91bde/nsp/metrics/denotation_accuracy.py#L46

Then, the logical form could be executed against the KB.

Best,
Jonathan

**Comment by rhythmcao** [comment]
Got it. Those variables are only needed during evaluation. Thanks a lot.
